services:
  # Lasticsearch for Logs
  elasticsearch_logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elastic_logs
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=logs-cluster
    ports:
      - "9201:9200"
    volumes:
      - elastic_logs_data:/usr/share/elasticsearch/data
    networks:
      - finance-rag-de_finance-rag-backend
  
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - finance-rag-de_finance-rag-backend
  
  # Fluentd
  fluentd:
    image: fluent/fluentd:v1.17-1
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "24224:24224"
    networks:
      - finance-rag-de_finance-rag-backend

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_finance_rag
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - finance-rag-de_finance-rag-backend

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - finance-rag-de_finance-rag-backend

volumes:
  elastic_data:
  prometheus_data:
  elastic_logs_data:
networks:
  finance-rag-de_finance-rag-backend:
    external: true