services:
  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - finance-rag-backend

  # Etcd for Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: milvus-etcd
    command: >
      etcd --name milvus-etcd
          --data-dir /etcd-data
          --listen-client-urls http://0.0.0.0:2379
          --advertise-client-urls http://milvus-etcd:2379
    networks:
      - finance-rag-backend

  # Milvus in standalone
  milvus:
    image: milvusdb/milvus:v2.3.5
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     
    depends_on:
      - etcd
      - minio
    networks:
      - finance-rag-backend

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finance-rag-backend
  
  # Elastic Search for Lexical search
  elasticsearch_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elastic_search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=search-cluster
    ports:
      - "9202:9200"
    volumes:
      - elastic_search_finance_data:/usr/share/elasticsearch/data
    networks:
      - finance-rag-backend

networks:
  finance-rag-backend:
    driver: bridge

volumes:
  minio_data:
  elastic_search_finance_data: